// cards.js
let cards = [

    /* ===== A1 ===== */
    { front: "bolmak", back: "sein" },
    { front: "bolmak (eýe bolmak)", back: "haben" },
    { front: "bolup galmak / bolmak", back: "werden" },
    { front: "gitmek", back: "gehen" },
    { front: "gelmek", back: "kommen" },
    { front: "galmak", back: "bleiben" },
    { front: "etmek / ýasamak", back: "machen" },
    { front: "etmek", back: "tun" },
    { front: "aýtmak", back: "sagen" },
    { front: "görmek", back: "sehen" },
    { front: "bermek", back: "geben" },
    { front: "almak", back: "nehmen" },
    { front: "getirmek", back: "bringen" },
    { front: "alyp gelmek", back: "holen" },
    { front: "öwrenmek", back: "lernen" },
    { front: "oýnamak", back: "spielen" },
    { front: "ýaşamak (ýaşaýyş)", back: "wohnen" },
    { front: "ýaşamak", back: "leben" },
    { front: "ady bolmak", back: "heißen" },
    { front: "soramak", back: "fragen" },
    { front: "jogap bermek", back: "antworten" },
    { front: "iýmək", back: "essen" },
    { front: "içmek", back: "trinken" },
    { front: "uklamak", back: "schlafen" },
    { front: "ylgamak / ýöremek", back: "laufen" },
    { front: "sürmek / ulag bilen gitmek", back: "fahren" },
    { front: "uçmak", back: "fliegen" },
    { front: "satyn almak", back: "kaufen" },
    { front: "tölemek", back: "bezahlen" },
    { front: "nahar bişirmek", back: "kochen" },
    { front: "açmak", back: "öffnen" },
    { front: "ýapmak", back: "schließen" },
    { front: "kömek etmek", back: "helfen" },
    { front: "başlamak", back: "beginnen" },
    { front: "tamamlamak / gutarmak", back: "enden" },
    { front: "okamak (uni)", back: "studieren" },
    { front: "türgenleşmek / maşk etmek", back: "üben" },
    { front: "söýmek", back: "lieben" },
    { front: "ýigrenmek", back: "hassen" },

    /* ===== A2 ===== */
    { front: "geplemek", back: "sprechen" },
    { front: "gürleşmek", back: "reden" },
    { front: "gürrüň bermek", back: "erzählen" },
    { front: "eşitmek", back: "hören" },
    { front: "diňlemek", back: "zuhören" },
    { front: "düşünmek", back: "verstehen" },
    { front: "düşündirmek", back: "erklären" },
    { front: "pikir etmek", back: "meinen" },
    { front: "ynanmak", back: "glauben" },
    { front: "bilmek (fakt)", back: "wissen" },
    { front: "tanymak", back: "kennen" },
    { front: "ýatdan çykarmak", back: "vergessen" },
    { front: "ýatlamak", back: "erinnern" },
    { front: "islemek", back: "möchten" },
    { front: "duýmak", back: "fühlen" },
    { front: "umyt etmek", back: "hoffen" },
    { front: "synanyşmak", back: "versuchen" },
    { front: "gerek bolmak", back: "brauchen" },
    { front: "ýetip gelmek", back: "ankommen" },
    { front: "ugramak / gitmek", back: "abfahren" },
    { front: "bile gelmek", back: "mitkommen" },
    { front: "yza dolanmak", back: "zurückkommen" },
    { front: "çakylyk bermek", back: "einladen" },
    { front: "jaň etmek", back: "anrufen" },
    { front: "garşylap almak", back: "abholen" },
    { front: "myhmançylyk etmek", back: "besuchen" },
    { front: "duşuşmak", back: "treffen" },
    { front: "başlamak", back: "anfangen" },
    { front: "bes etmek", back: "aufhören" },
    { front: "gözlemek", back: "suchen" },
    { front: "ýitirmek", back: "verlieren" },
    { front: "ýeňmek", back: "gewinnen" },
    { front: "ugratmak", back: "schicken" },
    { front: "almak (alyp bolmak)", back: "bekommen" },
    { front: "bahasy bolmak", back: "kosten" },
    { front: "syýahat etmek", back: "reisen" },

    /* Reflexive */
    { front: "şatlanmak", back: "sich freuen" },
    { front: "gyzyklanmak", back: "sich interessieren" },
    { front: "ötünç soramak", back: "sich entschuldigen" },
    { front: "ýuwunmak", back: "sich waschen" },
    { front: "duýmak", back: "sich fühlen" },

    /* ===== B1 ===== */
    { front: "pikirlenmek", back: "denken" },
    { front: "razylaşmak", back: "zustimmen" },
    { front: "ret etmek", back: "ablehnen" },
    { front: "garaşmak", back: "erwarten" },
    { front: "karar bermek", back: "entscheiden" },
    { front: "deňeşdirmek", back: "vergleichen" },
    { front: "suratlandyrmak", back: "beschreiben" },
    { front: "habar bermek", back: "berichten" },
    { front: "ara alyp maslahatlaşmak", back: "diskutieren" },
    { front: "habar ýetirmek", back: "mitteilen" },
    { front: "tanyşdyrmak", back: "vorstellen" },
    { front: "işlemek", back: "arbeiten" },
    { front: "işden çykmak", back: "kündigen" },
    { front: "işe almak", back: "einstellen" },
    { front: "arz etmek", back: "sich bewerben" },
    { front: "gatnaşmak", back: "teilnehmen" },
    { front: "guramak", back: "organisieren" },
    { front: "taýýarlamak", back: "vorbereiten" },
    { front: "amala aşyrmak", back: "durchführen" },
    { front: "meýilleşdirmek", back: "planen" },
    { front: "barlamak", back: "prüfen" },
    { front: "münmek", back: "einsteigen" },
    { front: "düşmek", back: "aussteigen" },
    { front: "çalyşmak", back: "umsteigen" },
    { front: "sypdyrmak", back: "verpassen" },
    { front: "ýetmek", back: "erreichen" },
    { front: "taşlamak / terk etmek", back: "verlassen" },
    { front: "yza dolanmak", back: "zurückkehren" },
    { front: "el çekmek", back: "aufgeben" },
    { front: "dowam etmek", back: "fortsetzen" },
    { front: "bile gatnaşmak", back: "mitmachen" },
    { front: "anyklamak", back: "feststellen" },
    { front: "bolup geçmek", back: "stattfinden" },
    { front: "ýatyryp goýmak", back: "abbrechen" },
    { front: "gowulandyrmak", back: "verbessern" },
    { front: "gaharlanmak", back: "sich ärgern" },
    { front: "geň galmak", back: "sich wundern" }
];
