// cards.js
let cards = [

    /* ===== A1 ===== */
    { front: "bolmak (to be)", back: "sein" , level:"A1" },
    { front: "bolmak (eýe bolmak)", back: "haben" , level:"A1" },
    { front: "bolup galmak / bolmak", back: "werden" , level:"A1" },
    { front: "gitmek", back: "gehen" , level:"A1" },
    { front: "gelmek", back: "kommen" , level:"A1" },
    { front: "galmak", back: "bleiben" , level:"A1" },
    { front: "etmek / ýasamak", back: "machen" , level:"A1" },
    { front: "etmek", back: "tun" , level:"A1" },
    { front: "aýtmak", back: "sagen" , level:"A1" },
    { front: "görmek", back: "sehen" , level:"A1" },
    { front: "bermek", back: "geben" , level:"A1" },
    { front: "almak", back: "nehmen" , level:"A1" },
    { front: "getirmek", back: "bringen" , level:"A1" },
    { front: "alyp gelmek", back: "holen" , level:"A1" },
    { front: "öwrenmek", back: "lernen" , level:"A1" },
    { front: "oýnamak", back: "spielen" , level:"A1" },
    { front: "ýaşamak (ýaşaýyş)", back: "wohnen" , level:"A1" },
    { front: "ýaşamak", back: "leben" , level:"A1" },
    { front: "ady bolmak", back: "heißen" , level:"A1" },
    { front: "soramak", back: "fragen" , level:"A1" },
    { front: "jogap bermek", back: "antworten" , level:"A1" },
    { front: "iýmək", back: "essen" , level:"A1" },
    { front: "içmek", back: "trinken" , level:"A1" },
    { front: "uklamak", back: "schlafen" , level:"A1" },
    { front: "ylgamak / ýöremek", back: "laufen" , level:"A1" },
    { front: "sürmek / ulag bilen gitmek", back: "fahren" , level:"A1" },
    { front: "uçmak", back: "fliegen" , level:"A1" },
    { front: "satyn almak", back: "kaufen" , level:"A1" },
    { front: "tölemek", back: "bezahlen" , level:"A1" },
    { front: "nahar bişirmek", back: "kochen" , level:"A1" },
    { front: "açmak", back: "öffnen" , level:"A1" },
    { front: "ýapmak", back: "schließen" , level:"A1" },
    { front: "kömek etmek", back: "helfen" , level:"A1" },
    { front: "başlamak", back: "beginnen" , level:"A1" },
    { front: "tamamlamak / gutarmak", back: "enden" , level:"A1" },
    { front: "okamak (uni)", back: "studieren" , level:"A1" },
    { front: "türgenleşmek / maşk etmek", back: "üben" , level:"A1" },
    { front: "söýmek", back: "lieben" , level:"A1" },
    { front: "ýigrenmek", back: "hassen" , level:"A1" },

    /* ===== A2 ===== */
    { front: "geplemek", back: "sprechen" , level:"A1" },
    { front: "gürleşmek", back: "reden" , level:"A1" },
    { front: "gürrüň bermek", back: "erzählen" , level:"A1" },
    { front: "eşitmek", back: "hören" , level:"A1" },
    { front: "diňlemek", back: "zuhören" , level:"A1" },
    { front: "düşünmek", back: "verstehen" , level:"A1" },
    { front: "düşündirmek", back: "erklären" , level:"A1" },
    { front: "pikir etmek", back: "meinen" , level:"A1" },
    { front: "ynanmak", back: "glauben" , level:"A1" },
    { front: "bilmek (fakt)", back: "wissen" , level:"A1" },
    { front: "tanymak", back: "kennen" , level:"A1" },
    { front: "ýatdan çykarmak", back: "vergessen" , level:"A1" },
    { front: "ýatlamak", back: "erinnern" , level:"A1" },
    { front: "islemek", back: "möchten" , level:"A1" },
    { front: "duýmak", back: "fühlen" , level:"A1" },
    { front: "umyt etmek", back: "hoffen" , level:"A1" },
    { front: "synanyşmak", back: "versuchen" , level:"A1" },
    { front: "gerek bolmak", back: "brauchen" , level:"A1" },
    { front: "ýetip gelmek", back: "ankommen" , level:"A1" },
    { front: "ugramak / gitmek", back: "abfahren" , level:"A1" },
    { front: "bile gelmek", back: "mitkommen" , level:"A1" },
    { front: "yza dolanmak", back: "zurückkommen" , level:"A1" },
    { front: "çakylyk bermek", back: "einladen" , level:"A1" },
    { front: "jaň etmek", back: "anrufen" , level:"A1" },
    { front: "garşylap almak", back: "abholen" , level:"A1" },
    { front: "myhmançylyk etmek", back: "besuchen" , level:"A1" },
    { front: "duşuşmak", back: "treffen" , level:"A1" },
    { front: "başlamak", back: "anfangen" , level:"A1" },
    { front: "bes etmek", back: "aufhören" , level:"A1" },
    { front: "gözlemek", back: "suchen" , level:"A1" },
    { front: "ýitirmek", back: "verlieren" , level:"A1" },
    { front: "ýeňmek", back: "gewinnen" , level:"A1" },
    { front: "ugratmak", back: "schicken" , level:"A1" },
    { front: "almak (alyp bolmak)", back: "bekommen" , level:"A1" },
    { front: "bahasy bolmak", back: "kosten" , level:"A1" },
    { front: "syýahat etmek", back: "reisen" , level:"A1" },

    /* Reflexive */
    { front: "şatlanmak", back: "sich freuen" , level:"A1" },
    { front: "gyzyklanmak", back: "sich interessieren" , level:"A1" },
    { front: "ötünç soramak", back: "sich entschuldigen" , level:"A1" },
    { front: "ýuwunmak", back: "sich waschen" , level:"A1" },
    { front: "duýmak", back: "sich fühlen" , level:"A1" },

    /* ===== B1 ===== */
    { front: "pikirlenmek", back: "denken" , level:"A1" },
    { front: "razylaşmak", back: "zustimmen" , level:"A1" },
    { front: "ret etmek", back: "ablehnen" , level:"A1" },
    { front: "garaşmak", back: "erwarten" , level:"A1" },
    { front: "karar bermek", back: "entscheiden" , level:"A1" },
    { front: "deňeşdirmek", back: "vergleichen" , level:"A1" },
    { front: "suratlandyrmak", back: "beschreiben" , level:"A1" },
    { front: "habar bermek", back: "berichten" , level:"A1" },
    { front: "ara alyp maslahatlaşmak", back: "diskutieren" , level:"A1" },
    { front: "habar ýetirmek", back: "mitteilen" , level:"A1" },
    { front: "tanyşdyrmak", back: "vorstellen" , level:"A1" },
    { front: "işlemek", back: "arbeiten" , level:"A1" },
    { front: "işden çykmak", back: "kündigen" , level:"A1" },
    { front: "işe almak", back: "einstellen" , level:"A1" },
    { front: "arz etmek", back: "sich bewerben" , level:"A1" },
    { front: "gatnaşmak", back: "teilnehmen" , level:"A1" },
    { front: "guramak", back: "organisieren" , level:"A1" },
    { front: "taýýarlamak", back: "vorbereiten" , level:"A1" },
    { front: "amala aşyrmak", back: "durchführen" , level:"A1" },
    { front: "meýilleşdirmek", back: "planen" , level:"A1" },
    { front: "barlamak", back: "prüfen" , level:"A1" },
    { front: "münmek", back: "einsteigen" , level:"A1" },
    { front: "düşmek", back: "aussteigen" , level:"A1" },
    { front: "çalyşmak", back: "umsteigen" , level:"A1" },
    { front: "sypdyrmak", back: "verpassen" , level:"A1" },
    { front: "ýetmek", back: "erreichen" , level:"A1" },
    { front: "taşlamak / terk etmek", back: "verlassen" , level:"A1" },
    { front: "yza dolanmak", back: "zurückkehren" , level:"A1" },
    { front: "el çekmek", back: "aufgeben" , level:"A1" },
    { front: "dowam etmek", back: "fortsetzen" , level:"A1" },
    { front: "bile gatnaşmak", back: "mitmachen" , level:"A1" },
    { front: "anyklamak", back: "feststellen" , level:"A1" },
    { front: "bolup geçmek", back: "stattfinden" , level:"A1" },
    { front: "ýatyryp goýmak", back: "abbrechen" , level:"A1" },
    { front: "gowulandyrmak", back: "verbessern" , level:"A1" },
    { front: "gaharlanmak", back: "sich ärgern" , level:"A1" },
    { front: "geň galmak", back: "sich wundern" , level:"A1" },


    /* ===== B2 ===== */
    // ===== Academic / Argumentation =====
    { front: "to claim", back: "behaupten — öňe sürmek" , level:"A1" },
    { front: "to assess", back: "einschätzen — bahalandyrmak" , level:"A1" },
    { front: "to take into account", back: "berücksichtigen — hasaba almak / nazar almak" , level:"A1" },
    { front: "to doubt", back: "bezweifeln — şübhelenmek" , level:"A1" },
    { front: "to emphasize", back: "betonen — nygtamak / ünsi çekmek" , level:"A1" },
    { front: "to assume", back: "vermuten — çaklamak / çakdyrmak" , level:"A1" },
    { front: "to refute", back: "widerlegen — ret etmek / inkär etmek" , level:"A1" },
    { front: "to convince", back: "überzeugen — ynandyrmak" , level:"A1" },
    { front: "to justify", back: "rechtfertigen — aklamak / esaslandyrmak" , level:"A1" },
    { front: "to criticize", back: "kritisieren — tankytlamak" , level:"A1" },

    // ===== Expressing ideas =====
    { front: "to express (an opinion)", back: "äußern — pikirini aýtmak" , level:"A1" },
    { front: "to explain clearly", back: "darlegen — düşnükli düşündirmek" , level:"A1" },
    { front: "to elaborate", back: "erläutern — jikme-jik düşündirmek" , level:"A1" },
    { front: "to summarize", back: "zusammenfassen — jemlemek / gysgaça beýan etmek" , level:"A1" },
    { front: "to negotiate", back: "verhandeln — gepleşik geçirmek" , level:"A1" },
    { front: "to argue", back: "argumentieren — delil getirmek / delillendirmek" , level:"A1" },
    { front: "to mention", back: "erwähnen — agzamak / belläp geçmek" , level:"A1" },
    { front: "to contradict", back: "widersprechen — garşy çykmak" , level:"A1" },

    // ===== Responsibility / Action =====
    { front: "to take over / assume responsibility", back: "übernehmen — jogapkärçiligi öz üstüne almak" , level:"A1" },
    { front: "to contribute", back: "beitragen — goşant goşmak" , level:"A1" },
    { front: "to evaluate", back: "bewerten — bahalandyrmak" , level:"A1" },
    { front: "to promote / support", back: "fördern — goldamak / ilerletmek" , level:"A1" },
    { front: "to demand", back: "verlangen — talap etmek" , level:"A1" },
    { front: "to concern", back: "betreffen — degmek / aladalandyrmak" , level:"A1" },
    { front: "to enable", back: "ermöglichen — mümkin etmek" , level:"A1" },
    { front: "to avoid", back: "vermeiden — gaça durmak / ýüz öwürmek" , level:"A1" },
    { front: "to influence", back: "beeinflussen — täsir etmek" , level:"A1" },
    { front: "to implement", back: "umsetzen — durmuşa geçirmek" , level:"A1" },

    // ===== Change / Process =====
    { front: "to arise", back: "entstehen — ýüze çykmak / dörmek" , level:"A1" },
    { front: "to develop", back: "entwickeln — ösdürmek / ösdürilmek" , level:"A1" },
    { front: "to change", back: "verändern — üýtgetmek" , level:"A1" },
    { front: "to increase", back: "steigern — artdyrmak" , level:"A1" },
    { front: "to reduce", back: "verringern — azaldyrmak" , level:"A1" },
    { front: "to replace", back: "ersetzen — çalyşmak / orny bilen alşyrmak" , level:"A1" },
    { front: "to expand", back: "erweitern — giňeltmek" , level:"A1" },
    { front: "to reduce (again)", back: "reduzieren — kemeltmek / azaldyrmak" , level:"A1" },

    // ===== Reflexive / Personal =====
    { front: "to complain", back: "sich beschweren — şikaýat etmek" , level:"A1" },
    { front: "to make an effort", back: "sich bemühen — tagallamak" , level:"A1" },
    { front: "to adapt", back: "sich anpassen — uýgunlaşmak" , level:"A1" },
    { front: "to concentrate", back: "sich konzentrieren — ünsi jemlemek" , level:"A1" },
    { front: "to behave", back: "sich verhalten — özüni alyp barmak" , level:"A1" },
    { front: "to develop oneself", back: "sich entwickeln — özüni ösdürmek" , level:"A1" },

    // ===== Results / Handling =====
    { front: "to have an effect", back: "sich auswirken — täsir etmek / netijä ýetirmek" , level:"A1" },
    { front: "to proceed", back: "vorgehen — öňe gitmek / ädim basmak" , level:"A1" },
    { front: "to record / hold onto", back: "festhalten — saklamak / tutmak" , level:"A1" },
    { front: "to prove", back: "nachweisen — subut etmek" , level:"A1" },
    { front: "to introduce", back: "einführen — girizmek / tanyşdyrmak" , level:"A1" },
    { front: "to deal with", back: "umgehen (mit) — işlemegi bilmek / ýüzlenmek" }
];
